apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      nodeSelector: # Add nodeSelector section
        kubernetes.io/hostname: kubenode02 # Specify the node name
      containers:
        - name: worker-app
          image: 192.168.1.138:5000/test_worker:v1
